# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-13 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationWestaflex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enregistreprocedure',
            name='id_procedure',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
