# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-13 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationWestaflex', '0002_auto_20180513_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enregistreprocedure',
            name='id_procedure',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
